/* Generated by Yosys 0.60+88 (git sha1 35321cd29-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:20" *)
(* generator = "Amaranth" *)
module top(addr, data, clk, rst, scl, sda_oe, ready, start);
  reg \$auto$verilog_backend.cc:2434:dump_module$1  = 0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:10" *)
  input [6:0] addr;
  wire [6:0] addr;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:11" *)
  input [7:0] data;
  wire [7:0] data;
  (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:7" *)
  output scl;
  reg scl = 1'h1;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:8" *)
  output sda_oe;
  reg sda_oe = 1'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:12" *)
  output ready;
  reg ready = 1'h1;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:9" *)
  input start;
  wire start;
  wire \$1 ;
  wire [16:0] \$10 ;
  wire \$11 ;
  wire [16:0] \$12 ;
  wire \$13 ;
  wire [1:0] \$14 ;
  wire \$15 ;
  wire \$16 ;
  wire \$17 ;
  wire \$18 ;
  reg \$19 ;
  wire [1:0] \$2 ;
  reg \$20 ;
  reg \$21 ;
  reg [15:0] \$22 ;
  reg [4:0] \$23 ;
  reg \$24 ;
  reg [1:0] \$25 ;
  wire \$3 ;
  wire \$4 ;
  wire [5:0] \$5 ;
  wire \$6 ;
  wire \$7 ;
  wire \$8 ;
  wire \$9 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:15" *)
  reg [4:0] bit_cnt = 5'h00;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:17" *)
  reg div_cnt = 1'h0;
  (* src = "C:\\Python314\\Lib\\contextlib.py:148" *)
  reg [1:0] i2c_master_state = 2'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:16" *)
  reg [15:0] shift_reg = 16'h0000;
  assign \$1  = div_cnt < (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:40" *) 1'h1;
  assign \$2  = div_cnt + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:41" *) 1'h1;
  assign \$3  = ~ (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:43" *) scl;
  assign \$5  = bit_cnt + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:46" *) 1'h1;
  assign \$6  = bit_cnt == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:48" *) 3'h7;
  assign \$7  = bit_cnt == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:53" *) 4'h8;
  assign \$8  = bit_cnt == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:55" *) 5'h11;
  assign \$9  = bit_cnt == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:57" *) 5'h12;
  assign \$11  = ~ (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:62" *) shift_reg[15];
  assign \$13  = div_cnt < (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:67" *) 1'h1;
  assign \$14  = div_cnt + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:68" *) 1'h1;
  assign \$15  = ! (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:71" *) scl;
  assign \$16  = ! (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) i2c_master_state;
  assign \$17  = i2c_master_state == (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) 1'h1;
  assign \$18  = i2c_master_state == (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) 2'h2;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:7" *)
  always @(posedge clk)
    scl <= \$19 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:8" *)
  always @(posedge clk)
    sda_oe <= \$20 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:12" *)
  always @(posedge clk)
    ready <= \$21 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:16" *)
  always @(posedge clk)
    shift_reg <= \$22 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:15" *)
  always @(posedge clk)
    bit_cnt <= \$23 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_master.py:17" *)
  always @(posedge clk)
    div_cnt <= \$24 ;
  (* src = "C:\\Python314\\Lib\\contextlib.py:148" *)
  always @(posedge clk)
    i2c_master_state <= \$25 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$19  = scl;
    casez (i2c_master_state)
      2'h0:
          \$19  = 1'h1;
      2'h1:
          (* full_case = 32'd1 *)
          if (\$1 ) begin
          end else begin
            \$19  = \$3 ;
          end
      2'h2:
          (* full_case = 32'd1 *)
          if (\$13 ) begin
          end else begin
            if (\$15 ) begin
              \$19  = 1'h1;
            end
          end
    endcase
    if (rst) begin
      \$19  = 1'h1;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$20  = sda_oe;
    casez (i2c_master_state)
      2'h0:
        begin
          \$20  = 1'h0;
          if (start) begin
            \$20  = 1'h1;
          end
        end
      2'h1:
          (* full_case = 32'd1 *)
          if (\$1 ) begin
          end else begin
            if (\$4 ) begin
              (* full_case = 32'd1 *)
              if (\$6 ) begin
                \$20  = 1'h0;
              end else if (\$7 ) begin
                \$20  = 1'h0;
              end else if (\$8 ) begin
                \$20  = 1'h0;
              end else if (\$9 ) begin
                \$20  = 1'h1;
              end else begin
                \$20  = \$11 ;
              end
            end
          end
      2'h2:
          (* full_case = 32'd1 *)
          if (\$13 ) begin
          end else begin
            (* full_case = 32'd1 *)
            if (\$15 ) begin
            end else begin
              \$20  = 1'h0;
            end
          end
    endcase
    if (rst) begin
      \$20  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$21  = ready;
    casez (i2c_master_state)
      2'h0:
        begin
          \$21  = 1'h1;
          if (start) begin
            \$21  = 1'h0;
          end
        end
    endcase
    if (rst) begin
      \$21  = 1'h1;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$22  = shift_reg;
    casez (i2c_master_state)
      2'h0:
          if (start) begin
            \$22  = { addr, 1'h0, data };
          end
      2'h1:
          (* full_case = 32'd1 *)
          if (\$1 ) begin
          end else begin
            if (\$4 ) begin
              (* full_case = 32'd1 *)
              if (\$6 ) begin
                \$22  = \$10 [15:0];
              end else if (\$7 ) begin
              end else if (\$8 ) begin
              end else if (\$9 ) begin
              end else begin
                \$22  = \$12 [15:0];
              end
            end
          end
    endcase
    if (rst) begin
      \$22  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$23  = bit_cnt;
    casez (i2c_master_state)
      2'h0:
          if (start) begin
            \$23  = 5'h00;
          end
      2'h1:
          (* full_case = 32'd1 *)
          if (\$1 ) begin
          end else begin
            if (\$4 ) begin
              \$23  = \$5 [4:0];
            end
          end
    endcase
    if (rst) begin
      \$23  = 5'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$24  = div_cnt;
    casez (i2c_master_state)
      2'h0:
          if (start) begin
            \$24  = 1'h0;
          end
      2'h1:
          (* full_case = 32'd1 *)
          if (\$1 ) begin
            \$24  = \$2 [0];
          end else begin
            \$24  = 1'h0;
          end
      2'h2:
          (* full_case = 32'd1 *)
          if (\$13 ) begin
            \$24  = \$14 [0];
          end else begin
            \$24  = 1'h0;
          end
    endcase
    if (rst) begin
      \$24  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$25  = i2c_master_state;
    casez (i2c_master_state)
      2'h0:
          if (start) begin
            \$25  = 2'h1;
          end
      2'h1:
          (* full_case = 32'd1 *)
          if (\$1 ) begin
          end else begin
            if (\$4 ) begin
              if (\$6 ) begin
              end else if (\$7 ) begin
              end else if (\$8 ) begin
              end else if (\$9 ) begin
                \$25  = 2'h2;
              end
            end
          end
      2'h2:
          (* full_case = 32'd1 *)
          if (\$13 ) begin
          end else begin
            (* full_case = 32'd1 *)
            if (\$15 ) begin
            end else begin
              \$25  = 2'h0;
            end
          end
    endcase
    if (rst) begin
      \$25  = 2'h0;
    end
  end
  assign \$4  = scl;
  assign \$10  = { shift_reg, 1'h0 };
  assign \$12  = { shift_reg, 1'h0 };
endmodule
