/* Generated by Yosys 0.60+88 (git sha1 35321cd29-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:24" *)
(* generator = "Amaranth" *)
module top(sda_i, clk, rst, sda_oe, data_out, valid, scl);
  reg \$auto$verilog_backend.cc:2434:dump_module$1  = 0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:8" *)
  input sda_i;
  wire sda_i;
  (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:9" *)
  output sda_oe;
  reg sda_oe = 1'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:10" *)
  output [7:0] data_out;
  reg [7:0] data_out = 8'h00;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:11" *)
  output valid;
  reg valid = 1'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:7" *)
  input scl;
  wire scl;
  wire [4:0] \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire \$13 ;
  wire \$14 ;
  wire \$15 ;
  wire \$16 ;
  wire \$17 ;
  wire \$18 ;
  reg [2:0] \$19 ;
  wire \$2 ;
  reg [2:0] \$20 ;
  reg \$21 ;
  reg \$22 ;
  reg [3:0] \$23 ;
  reg [7:0] \$24 ;
  reg [1:0] \$25 ;
  reg [7:0] \$26 ;
  wire \$3 ;
  wire \$4 ;
  wire \$5 ;
  wire [4:0] \$6 ;
  wire \$7 ;
  wire \$8 ;
  wire \$9 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:20" *)
  reg [3:0] bit_cnt = 4'h0;
  (* src = "C:\\Python314\\Lib\\contextlib.py:148" *)
  reg [1:0] fsm_state = 2'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:19" *)
  wire scl_falling;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:15" *)
  reg [2:0] scl_r = 3'h7;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:18" *)
  wire scl_rising;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:14" *)
  reg [2:0] sda_r = 3'h7;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:21" *)
  reg [7:0] shift_reg = 8'h00;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:16" *)
  wire start_cond;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:17" *)
  wire stop_cond;
  assign \$1  = bit_cnt + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:58" *) 1'h1;
  assign \$2  = bit_cnt == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:60" *) 4'h8;
  assign \$3  = shift_reg[7:1] == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:61" *) 7'h50;
  assign \$4  = ! (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:74" *) bit_cnt;
  assign \$5  = bit_cnt < (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:76" *) 4'h9;
  assign \$6  = bit_cnt + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:78" *) 1'h1;
  assign \$7  = bit_cnt == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:80" *) 1'h1;
  assign \$8  = bit_cnt == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:82" *) 4'h9;
  assign \$9  = ~ (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:31" *) scl_r[2];
  assign scl_rising = scl_r[1] & (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:31" *) \$9 ;
  assign \$10  = ~ (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:32" *) scl_r[1];
  assign scl_falling = \$10  & (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:32" *) scl_r[2];
  assign \$11  = ~ (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:33" *) sda_r[1];
  assign \$12  = \$11  & (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:33" *) sda_r[2];
  assign start_cond = scl_r[1] & (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:33" *) \$12 ;
  assign \$13  = ~ (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:34" *) sda_r[2];
  assign \$14  = sda_r[1] & (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:34" *) \$13 ;
  assign stop_cond = scl_r[1] & (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:34" *) \$14 ;
  assign \$15  = ! (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) fsm_state;
  assign \$16  = fsm_state == (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) 1'h1;
  assign \$17  = fsm_state == (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) 2'h2;
  assign \$18  = fsm_state == (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) 2'h3;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:14" *)
  always @(posedge clk)
    sda_r <= \$19 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:15" *)
  always @(posedge clk)
    scl_r <= \$20 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:9" *)
  always @(posedge clk)
    sda_oe <= \$21 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:11" *)
  always @(posedge clk)
    valid <= \$22 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:20" *)
  always @(posedge clk)
    bit_cnt <= \$23 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:21" *)
  always @(posedge clk)
    shift_reg <= \$24 ;
  (* src = "C:\\Python314\\Lib\\contextlib.py:148" *)
  always @(posedge clk)
    fsm_state <= \$25 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\I2C\\I2C_slave.py:10" *)
  always @(posedge clk)
    data_out <= \$26 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$19  = { sda_r[1:0], sda_i };
    if (rst) begin
      \$19  = 3'h7;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$20  = { scl_r[1:0], scl };
    if (rst) begin
      \$20  = 3'h7;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$21  = sda_oe;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      2'h0:
          \$21  = 1'h0;
      2'h1:
          if (start_cond) begin
          end else if (stop_cond) begin
          end else if (scl_rising) begin
          end else if (scl_falling) begin
            if (\$2 ) begin
              if (\$3 ) begin
                \$21  = 1'h1;
              end
            end
          end
      2'h2:
          if (start_cond) begin
          end else if (stop_cond) begin
          end else if (scl_rising) begin
          end else if (scl_falling) begin
            if (\$7 ) begin
              \$21  = 1'h0;
            end else if (\$8 ) begin
              \$21  = 1'h1;
            end
          end
      2'h3:
          if (start_cond) begin
            \$21  = 1'h0;
          end else if (stop_cond) begin
            \$21  = 1'h0;
          end else if (scl_falling) begin
            \$21  = 1'h0;
          end
    endcase
    if (rst) begin
      \$21  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$22  = valid;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      2'h0:
          \$22  = 1'h0;
      2'h1:
          /* empty */;
      2'h2:
          if (start_cond) begin
          end else if (stop_cond) begin
          end else if (scl_rising) begin
          end else if (scl_falling) begin
            if (\$7 ) begin
            end else if (\$8 ) begin
              \$22  = 1'h1;
            end
          end
      2'h3:
          \$22  = 1'h0;
    endcase
    if (rst) begin
      \$22  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$23  = bit_cnt;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      2'h0:
          if (start_cond) begin
            \$23  = 4'h0;
          end
      2'h1:
          if (start_cond) begin
            \$23  = 4'h0;
          end else if (stop_cond) begin
          end else if (scl_rising) begin
            \$23  = \$1 [3:0];
          end else if (scl_falling) begin
            if (\$2 ) begin
              if (\$3 ) begin
                \$23  = 4'h0;
              end
            end
          end
      2'h2:
          if (start_cond) begin
            \$23  = 4'h0;
          end else if (stop_cond) begin
          end else if (scl_rising) begin
            if (\$4 ) begin
              \$23  = 4'h1;
            end else if (\$5 ) begin
              \$23  = \$6 [3:0];
            end
          end
      2'h3:
          if (start_cond) begin
            \$23  = 4'h0;
          end else if (stop_cond) begin
          end else if (scl_falling) begin
            \$23  = 4'h1;
          end
    endcase
    if (rst) begin
      \$23  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$24  = shift_reg;
    casez (fsm_state)
      2'h0:
          if (start_cond) begin
            \$24  = 8'h00;
          end
      2'h1:
          if (start_cond) begin
            \$24  = 8'h00;
          end else if (stop_cond) begin
          end else if (scl_rising) begin
            \$24  = { shift_reg[6:0], sda_r[1] };
          end
      2'h2:
          if (start_cond) begin
            \$24  = 8'h00;
          end else if (stop_cond) begin
          end else if (scl_rising) begin
            if (\$4 ) begin
            end else if (\$5 ) begin
              \$24  = { shift_reg[6:0], sda_r[1] };
            end
          end
    endcase
    if (rst) begin
      \$24  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$25  = fsm_state;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      2'h0:
          if (start_cond) begin
            \$25  = 2'h1;
          end
      2'h1:
          if (start_cond) begin
            \$25  = 2'h1;
          end else if (stop_cond) begin
            \$25  = 2'h0;
          end else if (scl_rising) begin
          end else if (scl_falling) begin
            if (\$2 ) begin
              (* full_case = 32'd1 *)
              if (\$3 ) begin
                \$25  = 2'h2;
              end else begin
                \$25  = 2'h0;
              end
            end
          end
      2'h2:
          if (start_cond) begin
            \$25  = 2'h1;
          end else if (stop_cond) begin
            \$25  = 2'h0;
          end else if (scl_rising) begin
          end else if (scl_falling) begin
            if (\$7 ) begin
            end else if (\$8 ) begin
              \$25  = 2'h3;
            end
          end
      2'h3:
          if (start_cond) begin
            \$25  = 2'h1;
          end else if (stop_cond) begin
            \$25  = 2'h0;
          end else if (scl_falling) begin
            \$25  = 2'h2;
          end
    endcase
    if (rst) begin
      \$25  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$26  = data_out;
    casez (fsm_state)
      2'h0:
          /* empty */;
      2'h1:
          /* empty */;
      2'h2:
          if (start_cond) begin
          end else if (stop_cond) begin
          end else if (scl_rising) begin
          end else if (scl_falling) begin
            if (\$7 ) begin
            end else if (\$8 ) begin
              \$26  = shift_reg;
            end
          end
    endcase
    if (rst) begin
      \$26  = 8'h00;
    end
  end
endmodule
