/* Generated by Yosys 0.60+88 (git sha1 35321cd29-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:20" *)
(* generator = "Amaranth" *)
module top(data_in, miso, clk, rst, sck, mosi, cs, data_out, ready, valid, start);
  reg \$auto$verilog_backend.cc:2434:dump_module$1  = 0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:10" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:11" *)
  input miso;
  wire miso;
  (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:12" *)
  output sck;
  reg sck = 1'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:13" *)
  output mosi;
  reg mosi = 1'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:14" *)
  output cs;
  reg cs = 1'h1;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:15" *)
  output [7:0] data_out;
  reg [7:0] data_out = 8'h00;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:16" *)
  output ready;
  reg ready = 1'h1;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:17" *)
  output valid;
  reg valid = 1'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:9" *)
  input start;
  wire start;
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  reg \$13 ;
  reg \$14 ;
  reg \$15 ;
  reg \$16 ;
  reg [7:0] \$17 ;
  reg \$18 ;
  reg [1:0] \$19 ;
  wire [2:0] \$2 ;
  reg [3:0] \$20 ;
  reg [1:0] \$21 ;
  reg [7:0] \$22 ;
  wire \$3 ;
  wire [4:0] \$4 ;
  wire \$5 ;
  wire [2:0] \$6 ;
  wire \$7 ;
  wire [2:0] \$8 ;
  wire \$9 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:22" *)
  reg [3:0] bit_cnt = 4'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:21" *)
  reg [1:0] clk_cnt = 2'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:23" *)
  reg [7:0] shift_reg = 8'h00;
  (* src = "C:\\Python314\\Lib\\contextlib.py:148" *)
  reg [1:0] spi_master_state = 2'h0;
  assign \$1  = clk_cnt == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:46" *) 1'h1;
  assign \$2  = clk_cnt + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:54" *) 1'h1;
  assign \$3  = clk_cnt == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:57" *) 1'h1;
  assign \$4  = bit_cnt + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:61" *) 1'h1;
  assign \$5  = bit_cnt == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:63" *) 3'h7;
  assign \$6  = clk_cnt + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:69" *) 1'h1;
  assign \$7  = clk_cnt == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:72" *) 1'h1;
  assign \$8  = clk_cnt + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:81" *) 1'h1;
  assign \$9  = ! (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) spi_master_state;
  assign \$10  = spi_master_state == (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) 1'h1;
  assign \$11  = spi_master_state == (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) 2'h2;
  assign \$12  = spi_master_state == (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) 2'h3;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:17" *)
  always @(posedge clk)
    valid <= \$13 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:14" *)
  always @(posedge clk)
    cs <= \$14 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:12" *)
  always @(posedge clk)
    sck <= \$15 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:16" *)
  always @(posedge clk)
    ready <= \$16 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:23" *)
  always @(posedge clk)
    shift_reg <= \$17 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:13" *)
  always @(posedge clk)
    mosi <= \$18 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:21" *)
  always @(posedge clk)
    clk_cnt <= \$19 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:22" *)
  always @(posedge clk)
    bit_cnt <= \$20 ;
  (* src = "C:\\Python314\\Lib\\contextlib.py:148" *)
  always @(posedge clk)
    spi_master_state <= \$21 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_master.py:15" *)
  always @(posedge clk)
    data_out <= \$22 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$13  = 1'h0;
    (* full_case = 32'd1 *)
    casez (spi_master_state)
      2'h0:
          /* empty */;
      2'h1:
          /* empty */;
      2'h2:
          /* empty */;
      2'h3:
          if (\$7 ) begin
            \$13  = 1'h1;
          end
    endcase
    if (rst) begin
      \$13  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$14  = cs;
    (* full_case = 32'd1 *)
    casez (spi_master_state)
      2'h0:
        begin
          \$14  = 1'h1;
          if (start) begin
            \$14  = 1'h0;
          end
        end
      2'h1:
          /* empty */;
      2'h2:
          /* empty */;
      2'h3:
          if (\$7 ) begin
            \$14  = 1'h1;
          end
    endcase
    if (rst) begin
      \$14  = 1'h1;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$15  = sck;
    casez (spi_master_state)
      2'h0:
          \$15  = 1'h0;
      2'h1:
          if (\$1 ) begin
            \$15  = 1'h1;
          end
      2'h2:
          if (\$3 ) begin
            \$15  = 1'h0;
          end
    endcase
    if (rst) begin
      \$15  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$16  = ready;
    (* full_case = 32'd1 *)
    casez (spi_master_state)
      2'h0:
        begin
          \$16  = 1'h1;
          if (start) begin
            \$16  = 1'h0;
          end
        end
      2'h1:
          /* empty */;
      2'h2:
          /* empty */;
      2'h3:
          if (\$7 ) begin
            \$16  = 1'h1;
          end
    endcase
    if (rst) begin
      \$16  = 1'h1;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$17  = shift_reg;
    casez (spi_master_state)
      2'h0:
          if (start) begin
            \$17  = data_in;
          end
      2'h1:
          if (\$1 ) begin
            \$17  = { shift_reg[6:0], miso };
          end
    endcase
    if (rst) begin
      \$17  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$18  = mosi;
    casez (spi_master_state)
      2'h0:
          if (start) begin
            \$18  = data_in[7];
          end
      2'h1:
          /* empty */;
      2'h2:
          if (\$3 ) begin
            (* full_case = 32'd1 *)
            if (\$5 ) begin
            end else begin
              \$18  = shift_reg[7];
            end
          end
    endcase
    if (rst) begin
      \$18  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$19  = clk_cnt;
    (* full_case = 32'd1 *)
    casez (spi_master_state)
      2'h0:
          if (start) begin
            \$19  = 2'h0;
          end
      2'h1:
          (* full_case = 32'd1 *)
          if (\$1 ) begin
            \$19  = 2'h0;
          end else begin
            \$19  = \$2 [1:0];
          end
      2'h2:
          (* full_case = 32'd1 *)
          if (\$3 ) begin
            \$19  = 2'h0;
          end else begin
            \$19  = \$6 [1:0];
          end
      2'h3:
          (* full_case = 32'd1 *)
          if (\$7 ) begin
          end else begin
            \$19  = \$8 [1:0];
          end
    endcase
    if (rst) begin
      \$19  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$20  = bit_cnt;
    casez (spi_master_state)
      2'h0:
          if (start) begin
            \$20  = 4'h0;
          end
      2'h1:
          /* empty */;
      2'h2:
          if (\$3 ) begin
            \$20  = \$4 [3:0];
          end
    endcase
    if (rst) begin
      \$20  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$21  = spi_master_state;
    (* full_case = 32'd1 *)
    casez (spi_master_state)
      2'h0:
          if (start) begin
            \$21  = 2'h1;
          end
      2'h1:
          if (\$1 ) begin
            \$21  = 2'h2;
          end
      2'h2:
          if (\$3 ) begin
            (* full_case = 32'd1 *)
            if (\$5 ) begin
              \$21  = 2'h3;
            end else begin
              \$21  = 2'h1;
            end
          end
      2'h3:
          if (\$7 ) begin
            \$21  = 2'h0;
          end
    endcase
    if (rst) begin
      \$21  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$22  = data_out;
    (* full_case = 32'd1 *)
    casez (spi_master_state)
      2'h0:
          /* empty */;
      2'h1:
          /* empty */;
      2'h2:
          /* empty */;
      2'h3:
          if (\$7 ) begin
            \$22  = shift_reg;
          end
    endcase
    if (rst) begin
      \$22  = 8'h00;
    end
  end
endmodule
