/* Generated by Yosys 0.60+88 (git sha1 35321cd29-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:17" *)
(* generator = "Amaranth" *)
module top(mosi, cs, data_in, clk, rst, miso, data_out, valid, sck);
  reg \$auto$verilog_backend.cc:2434:dump_module$1  = 0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:9" *)
  input mosi;
  wire mosi;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:10" *)
  input cs;
  wire cs;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:11" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:12" *)
  output miso;
  reg miso = 1'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:13" *)
  output [7:0] data_out;
  reg [7:0] data_out = 8'h00;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:14" *)
  output valid;
  reg valid = 1'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:8" *)
  input sck;
  wire sck;
  wire \$1 ;
  reg \$10 ;
  reg [7:0] \$11 ;
  reg \$12 ;
  reg [3:0] \$13 ;
  reg [7:0] \$14 ;
  wire \$2 ;
  wire \$3 ;
  wire [4:0] \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire \$7 ;
  reg \$8 ;
  reg \$9 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:30" *)
  reg [3:0] bit_cnt = 4'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:20" *)
  reg cs_r = 1'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:25" *)
  wire sck_fall;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:19" *)
  reg sck_r = 1'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:24" *)
  wire sck_rise;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:29" *)
  reg [7:0] shift_reg = 8'h00;
  assign \$1  = ~ (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:34" *) cs;
  assign \$2  = cs_r & (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:34" *) \$1 ;
  assign \$3  = ~ (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:40" *) cs_r;
  assign \$4  = bit_cnt + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:45" *) 1'h1;
  assign \$5  = bit_cnt == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:47" *) 3'h7;
  assign \$6  = ~ (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:26" *) sck_r;
  assign sck_rise = \$6  & (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:26" *) sck;
  assign \$7  = ~ (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:27" *) sck;
  assign sck_fall = sck_r & (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:27" *) \$7 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:19" *)
  always @(posedge clk)
    sck_r <= \$8 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:20" *)
  always @(posedge clk)
    cs_r <= \$9 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:14" *)
  always @(posedge clk)
    valid <= \$10 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:29" *)
  always @(posedge clk)
    shift_reg <= \$11 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:12" *)
  always @(posedge clk)
    miso <= \$12 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:30" *)
  always @(posedge clk)
    bit_cnt <= \$13 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\SPI\\SPI_slave.py:13" *)
  always @(posedge clk)
    data_out <= \$14 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$8  = sck;
    if (rst) begin
      \$8  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$9  = cs;
    if (rst) begin
      \$9  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$10  = 1'h0;
    if (\$2 ) begin
    end else if (\$3 ) begin
      if (sck_rise) begin
      end else if (sck_fall) begin
        if (\$5 ) begin
          \$10  = 1'h1;
        end
      end
    end
    if (rst) begin
      \$10  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$11  = shift_reg;
    if (\$2 ) begin
      \$11  = data_in;
    end else if (\$3 ) begin
      if (sck_rise) begin
        \$11  = { shift_reg[6:0], mosi };
      end
    end
    if (rst) begin
      \$11  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$12  = miso;
    (* full_case = 32'd1 *)
    if (\$2 ) begin
      \$12  = data_in[7];
    end else if (\$3 ) begin
      if (sck_rise) begin
      end else if (sck_fall) begin
        \$12  = shift_reg[7];
      end
    end else begin
      \$12  = 1'h0;
    end
    if (rst) begin
      \$12  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$13  = bit_cnt;
    if (\$2 ) begin
      \$13  = 4'h0;
    end else if (\$3 ) begin
      if (sck_rise) begin
      end else if (sck_fall) begin
        \$13  = \$4 [3:0];
      end
    end
    if (rst) begin
      \$13  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$14  = data_out;
    if (\$2 ) begin
    end else if (\$3 ) begin
      if (sck_rise) begin
      end else if (sck_fall) begin
        if (\$5 ) begin
          \$14  = shift_reg;
        end
      end
    end
    if (rst) begin
      \$14  = 8'h00;
    end
  end
endmodule
