/* Generated by Yosys 0.60+88 (git sha1 35321cd29-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:17" *)
(* generator = "Amaranth" *)
module top(tx_data, rx, clk, rst, tx, tx_ready, rx_data, rx_valid, tx_start);
  reg \$auto$verilog_backend.cc:2434:dump_module$1  = 0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:9" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:12" *)
  input rx;
  wire rx;
  (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:10" *)
  output tx;
  wire tx;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:11" *)
  output tx_ready;
  reg tx_ready = 1'h1;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:13" *)
  output [7:0] rx_data;
  reg [7:0] rx_data = 8'h00;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:14" *)
  output rx_valid;
  reg rx_valid = 1'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:8" *)
  input tx_start;
  wire tx_start;
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire [2:0] \$12 ;
  wire \$13 ;
  wire [2:0] \$14 ;
  wire \$15 ;
  wire [3:0] \$16 ;
  wire \$17 ;
  wire [2:0] \$18 ;
  reg \$19 ;
  wire \$2 ;
  reg [9:0] \$20 ;
  reg [1:0] \$21 ;
  reg [3:0] \$22 ;
  reg \$23 ;
  reg [1:0] \$24 ;
  reg [2:0] \$25 ;
  reg [1:0] \$26 ;
  reg [7:0] \$27 ;
  reg [7:0] \$28 ;
  wire \$3 ;
  wire \$4 ;
  wire \$5 ;
  wire [2:0] \$6 ;
  wire \$7 ;
  wire [4:0] \$8 ;
  wire \$9 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:46" *)
  reg [2:0] rx_bit_count = 3'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:45" *)
  reg [1:0] rx_clk_count = 2'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:47" *)
  reg [7:0] rx_reg = 8'h00;
  (* src = "C:\\Python314\\Lib\\contextlib.py:148" *)
  reg [1:0] rx_state_state = 2'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:20" *)
  reg [3:0] tx_bit_cnt = 4'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:21" *)
  reg [1:0] tx_clk_cnt = 2'h0;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:19" *)
  reg [9:0] tx_frame = 10'h3ff;
  assign \$1  = ! (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) rx_state_state;
  assign \$2  = rx_state_state == (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) 1'h1;
  assign \$3  = rx_state_state == (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) 2'h2;
  assign \$4  = rx_state_state == (* src = "C:\\Users\\mathi\\AppData\\Roaming\\Python\\Python314\\site-packages\\amaranth\\hdl\\_dsl.py:486" *) 2'h3;
  assign \$5  = tx_clk_cnt < (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:34" *) 2'h3;
  assign \$6  = tx_clk_cnt + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:35" *) 1'h1;
  assign \$7  = tx_bit_cnt < (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:39" *) 4'h9;
  assign \$8  = tx_bit_cnt + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:40" *) 1'h1;
  assign \$9  = ! (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:56" *) rx;
  assign \$10  = rx_clk_count == (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:60" *) 1'h1;
  assign \$11  = ! (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:61" *) rx;
  assign \$12  = rx_clk_count + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:67" *) 1'h1;
  assign \$13  = rx_clk_count < (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:70" *) 2'h3;
  assign \$14  = rx_clk_count + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:71" *) 1'h1;
  assign \$15  = rx_bit_count < (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:75" *) 3'h7;
  assign \$16  = rx_bit_count + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:76" *) 1'h1;
  assign \$17  = rx_clk_count < (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:82" *) 2'h3;
  assign \$18  = rx_clk_count + (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:83" *) 1'h1;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:11" *)
  always @(posedge clk)
    tx_ready <= \$19 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:19" *)
  always @(posedge clk)
    tx_frame <= \$20 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:21" *)
  always @(posedge clk)
    tx_clk_cnt <= \$21 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:20" *)
  always @(posedge clk)
    tx_bit_cnt <= \$22 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:14" *)
  always @(posedge clk)
    rx_valid <= \$23 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:45" *)
  always @(posedge clk)
    rx_clk_count <= \$24 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:46" *)
  always @(posedge clk)
    rx_bit_count <= \$25 ;
  (* src = "C:\\Python314\\Lib\\contextlib.py:148" *)
  always @(posedge clk)
    rx_state_state <= \$26 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:47" *)
  always @(posedge clk)
    rx_reg <= \$27 ;
  (* src = "G:\\My Drive\\_Schule\\_4CHEL_2025-26\\DIC\\Prozessorschnittstellen\\hardware\\UART\\main.py:13" *)
  always @(posedge clk)
    rx_data <= \$28 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$19  = tx_ready;
    (* full_case = 32'd1 *)
    if (tx_ready) begin
      if (tx_start) begin
        \$19  = 1'h0;
      end
    end else begin
      (* full_case = 32'd1 *)
      if (\$5 ) begin
      end else begin
        (* full_case = 32'd1 *)
        if (\$7 ) begin
        end else begin
          \$19  = 1'h1;
        end
      end
    end
    if (rst) begin
      \$19  = 1'h1;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$20  = tx_frame;
    (* full_case = 32'd1 *)
    if (tx_ready) begin
      if (tx_start) begin
        \$20  = { 1'h1, tx_data, 1'h0 };
      end
    end else begin
      (* full_case = 32'd1 *)
      if (\$5 ) begin
      end else begin
        \$20  = { 1'h1, tx_frame[9:1] };
      end
    end
    if (rst) begin
      \$20  = 10'h3ff;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$21  = tx_clk_cnt;
    (* full_case = 32'd1 *)
    if (tx_ready) begin
      if (tx_start) begin
        \$21  = 2'h0;
      end
    end else begin
      (* full_case = 32'd1 *)
      if (\$5 ) begin
        \$21  = \$6 [1:0];
      end else begin
        \$21  = 2'h0;
      end
    end
    if (rst) begin
      \$21  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$22  = tx_bit_cnt;
    (* full_case = 32'd1 *)
    if (tx_ready) begin
      if (tx_start) begin
        \$22  = 4'h0;
      end
    end else begin
      (* full_case = 32'd1 *)
      if (\$5 ) begin
      end else begin
        if (\$7 ) begin
          \$22  = \$8 [3:0];
        end
      end
    end
    if (rst) begin
      \$22  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$23  = rx_valid;
    (* full_case = 32'd1 *)
    casez (rx_state_state)
      2'h0:
          \$23  = 1'h0;
      2'h1:
          /* empty */;
      2'h2:
          /* empty */;
      2'h3:
          (* full_case = 32'd1 *)
          if (\$17 ) begin
          end else begin
            \$23  = 1'h1;
          end
    endcase
    if (rst) begin
      \$23  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$24  = rx_clk_count;
    (* full_case = 32'd1 *)
    casez (rx_state_state)
      2'h0:
          \$24  = 2'h0;
      2'h1:
          (* full_case = 32'd1 *)
          if (\$10 ) begin
            if (\$11 ) begin
              \$24  = 2'h0;
            end
          end else begin
            \$24  = \$12 [1:0];
          end
      2'h2:
          (* full_case = 32'd1 *)
          if (\$13 ) begin
            \$24  = \$14 [1:0];
          end else begin
            \$24  = 2'h0;
          end
      2'h3:
          (* full_case = 32'd1 *)
          if (\$17 ) begin
            \$24  = \$18 [1:0];
          end else begin
            \$24  = 2'h0;
          end
    endcase
    if (rst) begin
      \$24  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$25  = rx_bit_count;
    casez (rx_state_state)
      2'h0:
          \$25  = 3'h0;
      2'h1:
          /* empty */;
      2'h2:
          (* full_case = 32'd1 *)
          if (\$13 ) begin
          end else begin
            (* full_case = 32'd1 *)
            if (\$15 ) begin
              \$25  = \$16 [2:0];
            end else begin
              \$25  = 3'h0;
            end
          end
    endcase
    if (rst) begin
      \$25  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$26  = rx_state_state;
    (* full_case = 32'd1 *)
    casez (rx_state_state)
      2'h0:
          if (\$9 ) begin
            \$26  = 2'h1;
          end
      2'h1:
          if (\$10 ) begin
            (* full_case = 32'd1 *)
            if (\$11 ) begin
              \$26  = 2'h2;
            end else begin
              \$26  = 2'h0;
            end
          end
      2'h2:
          (* full_case = 32'd1 *)
          if (\$13 ) begin
          end else begin
            (* full_case = 32'd1 *)
            if (\$15 ) begin
            end else begin
              \$26  = 2'h3;
            end
          end
      2'h3:
          (* full_case = 32'd1 *)
          if (\$17 ) begin
          end else begin
            \$26  = 2'h0;
          end
    endcase
    if (rst) begin
      \$26  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$27  = rx_reg;
    casez (rx_state_state)
      2'h0:
          /* empty */;
      2'h1:
          /* empty */;
      2'h2:
          (* full_case = 32'd1 *)
          if (\$13 ) begin
          end else begin
            \$27  = { rx, rx_reg[7:1] };
          end
    endcase
    if (rst) begin
      \$27  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2434:dump_module$1 ) begin end
    \$28  = rx_data;
    (* full_case = 32'd1 *)
    casez (rx_state_state)
      2'h0:
          /* empty */;
      2'h1:
          /* empty */;
      2'h2:
          /* empty */;
      2'h3:
          (* full_case = 32'd1 *)
          if (\$17 ) begin
          end else begin
            \$28  = rx_reg;
          end
    endcase
    if (rst) begin
      \$28  = 8'h00;
    end
  end
  assign tx = tx_frame[0];
endmodule
